[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

board_build.partitions = huge_app.csv
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
board_microros_transport = wifi
board_microros_distro = humble

[env:native]
platform = native
test_build_src = true
build_src_filter = +<ld03_driver.cpp> +<scan_conversion.cpp>
build_flags = -std=gnu++11
